wmirror v1.2

diff --git a/wmirror b/wmirror
--- a/wmirror
+++ b/wmirror
@@ -37,21 +37,14 @@
 ################################################################################
 ################################################################################
 
-TDIR="/home/wuseman/websites"
-
-if [[ -z $TDIR ]]; then
-   printf "Please set a target dir for the folders that will be downloaded...\n"
-   exit 1
-fi
 
 usage() {
 cat << EOF
 
  Usage: ./wmirror.sh -u <url> [options]
 
-     -u|--url   <url>                       - This option is required and will set the url to target" 
-     -d|--depth <0-99>                      - Set a depth value for how many folders you wanna download...(Default: 5).
-     -q|--quiet <1>                       - Mirror the site without spamming to stdout, only use -q 1 if you want it to be quiet
+     -u                 - This option is required and will set the url to target" 
+     -p                 - Path to save your downloaded data
 
 EOF
 exit 1
@@ -60,37 +53,18 @@ exit 1
 if [[ -z $1 ]]; then usage;exit 1; fi
 
 
-while getopts "u:d:q:h" getopts; do
+while getopts ":u:p:" getopts; do
   case $getopts in
-    h) usage ;;
     u) u=$OPTARG ;;
-    d) d=$OPTARG
-         if [[ $d != [0-9] ]] && [[ $d != [0-9][0-9] ]]; then
-	 if [[ $d = [A-Za-z].* ]]; then
-	   printf "[\e[0;31m+\e[0m] - Depth must be used by a number...\n"
-	   exit 1
-	 fi
-	   printf "[\e[0;31m+\e[0m] - That's not a valid number, largest depth is 99..\n"
-	   exit 1
-	 fi  ;;
-    q) q=$OPTARG
-       (( q == 1 )) || usage ;;
-    \?) printf "[\e[0;31m+\e[0m] - Internal Error!"; exit 1 ;; 
-    *) printf "[\e[0;31m+\e[0m] - That's not a valid url.."; exit 1 ;;
+    p) p=$OPTARG ;;
+    \?) echo -e "$basename$0: internal error -- $* is not a valid option, exiting ...;" exit 1 ;; 
+    *) echo -e "$basename$0: internal error -- $* is not a valid option, exiting ...;" exit 1 ;; 
   esac
 done
 
-if [[ $q = "1" ]]; then
-       read -p "Please enter a description of this site: " DESC
-       echo -e "- $(date +%d-%m-%Y) | $(date +%H:%M:%S) | $u | $DESC" >> $TDIR/website_sites.txt
-       echo "Downloading $u..."
-       wget -nc -e robots=off -r -q $u -P "$TDIR"
-       printf "\e[7m%-`tput cols`s\e[0m\n" "Successfully mirrored: $u "
-       exit 1
-fi
-       read -p "Please enter a description of this site: " DESC
-       echo -e "- $(date +%d-%m-%Y) | $(date +%H:%M:%S) | $u | $DESC" >> $TDIR/website_sites.txt
-       echo "Downloading $u..."
-       wget -nc -q -e robots=off -r --show-progress $u -P "$TDIR/"
-       printf "\e[7m%-`tput cols`s\e[0m\n" "Successfully mirrored: $u "
-       exit 1
+echo -e "-------------------------------------"
+echo -e "Downloading $u ....."
+echo -e "-------------------------------------"
+wget -q --show-progress -l inf -m -e robots=off -P $p $u
+
+
